name: Auto Update XML/Readme Files Every Hour

on:
  schedule:
    - cron: '3 */1 * * *' # Runs every 1 hour
  workflow_dispatch:

jobs:
  update_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests pytz pyyaml bs4

      - name: Run update script for standalone XML
        continue-on-error: true
        run: |
          python3 .github/actions/generate_macos_standalone_latest.py
          git add latest_raw_files/*

      - name: Commit changes for standalone XML (if any)
        continue-on-error: true
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add latest_raw_files/*
          git commit -m "Auto updating standalone XML, YAML, JSON files" || echo "No changes to commit"
          git push https://github-actions[bot]:$TOKEN@github.com/cocopuff2u/macadmins_msft.git

      - name: Run update script for standalone update history
        continue-on-error: true
        run: |
          python3 .github/actions/generate_macos_standalone_update_history.py
          git add latest_raw_files/*

      - name: Commit changes for standalone update history (if any)
        continue-on-error: true
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add latest_raw_files/*
          git commit -m "Auto updating standalone update history XML, YAML, JSON files" || echo "No changes to commit"
          git push https://github-actions[bot]:$TOKEN@github.com/cocopuff2u/macadmins_msft.git

      - name: Run update script for standalone CVE history
        continue-on-error: true
        run: |
          python3 .github/actions/generate_macos_standalone_cve_history.py
          git add latest_raw_files/*

      - name: Commit changes for standalone CVE history (if any)
        continue-on-error: true
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add latest_raw_files/*
          git commit -m "Auto updating standalone CVE history XML, YAML, JSON files" || echo "No changes to commit"
          git push https://github-actions[bot]:$TOKEN@github.com/cocopuff2u/macadmins_msft.git

      - name: Run update script for macOS XML
        continue-on-error: true
        run: |
          python3 .github/actions/generate_macos_appstore_latest.py
          git add latest_raw_files/*

      - name: Commit changes for macOS XML (if any)
        continue-on-error: true
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add latest_raw_files/*
          git commit -m "Auto updating macOS XML, YAML, JSON files" || echo "No changes to commit"
          git push https://github-actions[bot]:$TOKEN@github.com/cocopuff2u/macadmins_msft.git

      - name: Run update script for iOS XML
        continue-on-error: true
        run: |
          python3 .github/actions/generate_ios_appstore_latest.py
          git add latest_raw_files/*

      - name: Commit changes for iOS XML (if any)
        continue-on-error: true
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add latest_raw_files/*
          git commit -m "Auto updating iOS XML, YAML, JSON files" || echo "No changes to commit"
          git push https://github-actions[bot]:$TOKEN@github.com/cocopuff2u/macadmins_msft.git

      - name: Run update script for OneDrive XML
        continue-on-error: true
        run: |
          python3 .github/actions/generate_onedrive_all.py
          git add latest_raw_files/*

      - name: Commit changes for OneDrive XML (if any)
        continue-on-error: true
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add latest_raw_files/*
          git commit -m "Auto updating iOS XML, YAML, JSON files" || echo "No changes to commit"
          git push https://github-actions[bot]:$TOKEN@github.com/cocopuff2u/macadmins_msft.git

      - name: Run update script for macOS standalone preview
        continue-on-error: true
        run: |
          python3 .github/actions/generate_macos_standalone_preview.py
          git add latest_raw_files/*

      - name: Commit changes for macOS standalone preview (if any)
        continue-on-error: true
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add latest_raw_files/*
          git commit -m "Auto updating macOS standalone preview XML, YAML, JSON files" || echo "No changes to commit"
          git push https://github-actions[bot]:$TOKEN@github.com/cocopuff2u/macadmins_msft.git

      - name: Run update script for macOS standalone beta
        continue-on-error: true
        run: |
          python3 .github/actions/generate_macos_standalone_beta.py
          git add latest_raw_files/*

      - name: Commit changes for macOS standalone beta (if any)
        continue-on-error: true
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add latest_raw_files/*
          git commit -m "Auto updating macOS standalone beta XML, YAML, JSON files" || echo "No changes to commit"
          git push https://github-actions[bot]:$TOKEN@github.com/cocopuff2u/macadmins_msft.git

      - name: Run update script for Edge XML
        continue-on-error: true
        run: |
          python3 .github/actions/generate_edge_all.py
          git add latest_raw_files/*

      - name: Commit changes for macOS Edge All (if any)
        continue-on-error: true
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add latest_raw_files/*
          git commit -m "Auto updating macOS Edge All XML, YAML, JSON files" || echo "No changes to commit"
          git push https://github-actions[bot]:$TOKEN@github.com/cocopuff2u/macadmins_msft.git

      - name: Run update script for RSS feed
        run: |
          python3 .github/actions/generate_macos_standalone_rss.py

      - name: Commit changes for RSS feed (if any)
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add latest_raw_files/*
          git commit -m "Auto Updating RSS Feed Files" || echo "No changes to commit"
          git push https://github-actions[bot]:$TOKEN@github.com/cocopuff2u/macadmins_msft.git

      - name: Run update script for README
        run: |
          python3 .github/actions/update_readme.py

      - name: Commit changes for README (if any)
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Auto Updating README File" || echo "No changes to commit"
          git push https://github-actions[bot]:$TOKEN@github.com/cocopuff2u/macadmins_msft.git